import sys,os
import logging

sys.path.insert(0, os.path.abspath('../'))
from utils.utils import initLogging, checkNcreateFolder

from plotting.style import StyleConfig

import checkInputData

basePath = os.path.expanduser("~/Code/TF4ttHFH")

plots = {
    #################################################################################################################################
    #################################################### Compare years #############################################################
    #################################################################################################################################
    # "CompYears_VR_Data_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/Data/VR/7J/comp_7J_data_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["Data/QCD 2016", "Data/QCD 2017", "Data/QCD 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_VR_Data_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/Data/VR/8J/comp_8J_data_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["Data/QCD 2016", "Data/QCD 2017", "Data/QCD 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_VR_Data_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/Data/VR/9J/comp_9J_data_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["Data/QCD 2016", "Data/QCD 2017", "Data/QCD 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_TR_Data_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_Data_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_Data_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_Data_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/Data/TR/7J/comp_7J_data_MWCentral",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["Data/QCD 2016", "Data/QCD 2017", "Data/QCD 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_TR_Data_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_Data_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_Data_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_Data_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/Data/TR/8J/comp_8J_data_MWCentral",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["Data/QCD 2016", "Data/QCD 2017", "Data/QCD 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_TR_Data_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_Data_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_Data_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_Data_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/Data/TR/9J/comp_9J_data_MWCentral",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["Data/QCD 2016", "Data/QCD 2017", "Data/QCD 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    #################################################################################################################################
    # "CompYears_VR_ttHbb_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/VR/7J/comp_7J_signal_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_VR_ttHbb_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/VR/8J/comp_8J_signal_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_VR_ttHbb_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/VR/9J/comp_9J_signal_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_TR_ttHbb_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_ttHbb_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/TR/7J/comp_7J_signal_MWCentral",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_TR_ttHbb_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_ttHbb_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/TR/8J/comp_8J_signal_MWCentral",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    # "CompYears_TR_ttHbb_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_ttHbb_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/TR/9J/comp_9J_signal_MWCentral",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : None,
    # },
    "CompYears_SR_ttHbb_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_SR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_SR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_SR_v1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/SR/7J/comp_7J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : None,
    },
    "CompYears_SR_ttHbb_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_SR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_SR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_SR_v1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/SR/8J/comp_8J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : None,
    },
    "CompYears_SR_ttHbb_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_SR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_SR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_SR_v1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/CompareYears/ttHbb/SR/9J/comp_9J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttHbb 2016", "ttHbb 2017", "ttHbb 2018"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : None,
    },
    #################################################################################################################################
    ###########################################  ______     _ _   _____             ___   ###########################################
    ########################################### |  ____|   | | | |  __ \           |__ \  ###########################################
    ########################################### | |__ _   _| | | | |__) |   _ _ __    ) | ###########################################
    ########################################### |  __| | | | | | |  _  / | | | '_ \  / /  ###########################################
    ########################################### | |  | |_| | | | | | \ \ |_| | | | |/ /_  ###########################################
    ########################################### |_|   \__,_|_|_| |_|  \_\__,_|_| |_|____| ###########################################
    ###########################################                                           ###########################################
    #################################################################################################################################                                         
    ################################################### Sample comp VR  #############################################################
    #################################################################################################################################
    # "FullRun2_VR_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHad_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_Data_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttH_vs_ttHad_vs_Data_VR/7J/comp_7J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : 137.1,
    # },
    # "FullRun2_VR_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHad_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_Data_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttH_vs_ttHad_vs_Data_VR/8J/comp_8J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : 137.1,
    # },
    # "FullRun2_VR_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHad_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_Data_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttH_vs_ttHad_vs_Data_VR/9J/comp_9J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : 137.1,
    # },
    #################################################################################################################################
    ########################################### Signal regions comp - Same sample ###################################################
    #################################################################################################################################
    "FullRun2_Data_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR_v1p1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR_v1p1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/Data_regionCompare/7J/regionComp_7J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_Data_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR_v1p1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR_v1p1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/Data_regionCompare/8J/regionComp_8J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_Data_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR_v1p1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR_v1p1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/Data_regionCompare/9J/regionComp_9J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_ttHbb_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR_v1p1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR_v1p1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_SR_v1p1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttHbb_regionCompare/7J/regionComp_7J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_ttHbb_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR_v1p1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR_v1p1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_SR_v1p1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttHbb_regionCompare/8J/regionComp_8J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_ttHbb_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR_v1p1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR_v1p1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_SR_v1p1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttHbb_regionCompare/9J/regionComp_9J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    #################################################################################################################################
    ############################################ Validation regions comp - Same sample  #############################################
    #################################################################################################################################
    "FullRun2_Data_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR2_v1p1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR2_v1p1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/Data_regionCompare_VR/7J/regionComp_7J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_Data_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR2_v1p1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR2_v1p1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/Data_regionCompare_VR/8J/regionComp_8J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_Data_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR2_v1p1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR2_v1p1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/Data_regionCompare_VR/9J/regionComp_9J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_ttHbb_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR2_v1p1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR2_v1p1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttHbb_regionCompare_VR/7J/regionComp_7J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_ttHbb_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR2_v1p1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR2_v1p1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttHbb_regionCompare_VR/8J/regionComp_8J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    "FullRun2_ttHbb_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_TR2_v1p1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_CR2_v1p1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/Combined/preprocData_Run2Legacy_Comb_VR_v1p1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/Combined/ttHbb_regionCompare_VR/9J/regionComp_9J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 137.1,
    },
    #################################################################################################################################
    #####################################################  ___   ___  __   __   #####################################################
    ##################################################### |__ \ / _ \/_ | / /   #####################################################
    #####################################################    ) | | | || |/ /_   #####################################################
    #####################################################   / /| | | || | '_ \  #####################################################
    #####################################################  / /_| |_| || | (_) | #####################################################
    ##################################################### |____|\___/ |_|\___/  #####################################################
    #####################################################                       #####################################################
    #################################################################################################################################
    ################################################### Sample comp VR  #############################################################
    #################################################################################################################################
    # "2016_VR_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHad_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttH_vs_ttHad_vs_Data_VR/7J/comp_7J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : 35.9,
    # },
    # "2016_VR_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHad_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttH_vs_ttHad_vs_Data_VR/8J/comp_8J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : 35.9,
    # },
    # "2016_VR_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHad_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttH_vs_ttHad_vs_Data_VR/9J/comp_9J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
    #     "lumi" : 35.9,
    # },
    #################################################################################################################################
    ########################################### Signal regions comp - Same sample ###################################################
    #################################################################################################################################
    "2016_Data_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR_v1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/Data_regionCompare/7J/regionComp_7J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_Data_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR_v1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/Data_regionCompare/8J/regionComp_8J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_Data_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR_v1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/Data_regionCompare/9J/regionComp_9J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_ttHbb_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_SR_v1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttHbb_regionCompare/7J/regionComp_7J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_ttHbb_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_SR_v1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttHbb_regionCompare/8J/regionComp_8J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_ttHbb_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_SR_v1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttHbb_regionCompare/9J/regionComp_9J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    #################################################################################################################################
    ############################################ Validation regions comp - Same sample  #############################################
    #################################################################################################################################
    "2016_Data_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR2_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR2_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/Data_regionCompare_VR/7J/regionComp_7J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_Data_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR2_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR2_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/Data_regionCompare_VR/8J/regionComp_8J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_Data_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR2_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR2_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/Data_regionCompare_VR/9J/regionComp_9J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_ttHbb_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR2_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR2_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttHbb_regionCompare_VR/7J/regionComp_7J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_ttHbb_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR2_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR2_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttHbb_regionCompare_VR/8J/regionComp_8J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    "2016_ttHbb_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_TR2_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_CR2_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2016/preprocData_Run2Legacy_2016_VR_v1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2016/ttHbb_regionCompare_VR/9J/regionComp_9J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*","btagNorm"],
        "lumi" : 35.9,
    },
    #################################################################################################################################
    #####################################################  ___   ___  __ ______  #####################################################
    ##################################################### |__ \ / _ \/_ |____  | #####################################################
    #####################################################    ) | | | || |   / /  #####################################################
    #####################################################   / /| | | || |  / /   #####################################################
    #####################################################  / /_| |_| || | / /    #####################################################
    ##################################################### |____|\___/ |_|/_/     #####################################################
    #####################################################                        #####################################################
    #################################################################################################################################
    ################################################### Sample comp VR  #############################################################
    #################################################################################################################################
    # "2017_VR_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHad_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttH_vs_ttHad_vs_Data_VR/7J/comp_7J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
    #     "lumi" : 41.5,
    # },
    # "2017_VR_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHad_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttH_vs_ttHad_vs_Data_VR/8J/comp_8J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
    #     "lumi" : 41.5,
    # },
    # "2017_VR_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHad_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttH_vs_ttHad_vs_Data_VR/9J/comp_9J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
    #     "lumi" : 41.5,
    # },
    #################################################################################################################################
    ########################################### Signal regions comp - Same sample ###################################################
    #################################################################################################################################
    "2017_Data_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR_v1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/Data_regionCompare/7J/regionComp_7J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_Data_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR_v1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/Data_regionCompare/8J/regionComp_8J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_Data_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR_v1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/Data_regionCompare/9J/regionComp_9J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_ttHbb_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_SR_v1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttHbb_regionCompare/7J/regionComp_7J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_ttHbb_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_SR_v1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttHbb_regionCompare/8J/regionComp_8J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_ttHbb_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_SR_v1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttHbb_regionCompare/9J/regionComp_9J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    #################################################################################################################################
    ############################################ Validation regions comp - Same sample  #############################################
    #################################################################################################################################
    "2017_Data_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR2_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR2_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/Data_regionCompare_VR/7J/regionComp_7J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_Data_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR2_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR2_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/Data_regionCompare_VR/8J/regionComp_8J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_Data_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR2_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR2_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/Data_regionCompare_VR/9J/regionComp_9J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_ttHbb_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR2_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR2_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttHbb_regionCompare_VR/7J/regionComp_7J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_ttHbb_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR2_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR2_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttHbb_regionCompare_VR/8J/regionComp_8J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    "2017_ttHbb_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_TR2_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_CR2_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2017/preprocData_Run2Legacy_2017_VR_v1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2017/ttHbb_regionCompare_VR/9J/regionComp_9J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 41.5,
    },
    #################################################################################################################################
    ##################################################### ___   ___  _ _  ___   #####################################################
    ##################################################### |__ \ / _ \/_ |/ _ \  #####################################################
    #####################################################    ) | | | || | (_) | #####################################################
    #####################################################   / /| | | || |> _ <  #####################################################
    #####################################################  / /_| |_| || | (_) | #####################################################
    ##################################################### |____|\___/ |_|\___/  #####################################################
    #####################################################                       #####################################################
    #################################################################################################################################
    ################################################### Sample comp VR  #############################################################
    #################################################################################################################################
    # "2018_VR_7J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHad_7J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_7J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttH_vs_ttHad_vs_Data_VR/7J/comp_7J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
    #     "lumi" : 59.7,
    # },
    # "2018_VR_8J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHad_8J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_8J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttH_vs_ttHad_vs_Data_VR/8J/comp_8J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
    #     "lumi" : 59.7,
    # },
    # "2018_VR_9J" : {
    #     "style" : basePath+"/data/plotStyle.cfg",
    #     "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHad_9J.h5",
    #                 basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_9J.h5"],
    #     "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttH_vs_ttHad_vs_Data_VR/9J/comp_9J_MWSidebands",
    #     "plotType" : "plotDist",
    #     "normalized" : True,
    #     "Legend" : ["ttH(bb)", "tt+Jets (FH)", "Data/QCD"],
    #     "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
    #     "lumi" : 59.7,
    # },
    #################################################################################################################################
    ########################################### Signal regions comp - Same sample ###################################################
    #################################################################################################################################
    "2018_Data_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR_v1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/Data_regionCompare/7J/regionComp_7J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_Data_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR_v1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/Data_regionCompare/8J/regionComp_8J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_Data_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR_v1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/Data_regionCompare/9J/regionComp_9J_data_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD TR", "Data/QCD CR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_ttHbb_regionCompare_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_SR_v1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttHbb_regionCompare/7J/regionComp_7J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_ttHbb_regionCompare_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_SR_v1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttHbb_regionCompare/8J/regionComp_8J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_ttHbb_regionCompare_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_SR_v1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttHbb_regionCompare/9J/regionComp_9J_signal_MWCentral",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) TR", "ttH(bb) CR", "ttH(bb) SR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    #################################################################################################################################
    ############################################ Validation regions comp - Same sample  #############################################
    #################################################################################################################################
    "2018_Data_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR2_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR2_v1_Data_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/Data_regionCompare_VR/7J/regionComp_7J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_Data_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR2_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR2_v1_Data_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/Data_regionCompare_VR/8J/regionComp_8J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_Data_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR2_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR2_v1_Data_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_Data_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/Data_regionCompare_VR/9J/regionComp_9J_data_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["Data/QCD ValTR", "Data/QCD ValCR", "Data/QCD VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_ttHbb_regionCompare_VR_7J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR2_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR2_v1_ttHbb_7J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_7J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttHbb_regionCompare_VR/7J/regionComp_7J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_ttHbb_regionCompare_VR_8J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR2_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR2_v1_ttHbb_8J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_8J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttHbb_regionCompare_VR/8J/regionComp_8J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
    "2018_ttHbb_regionCompare_VR_9J" : {
        "style" : basePath+"/data/plotStyle.cfg",
        "inputs" : [basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_TR2_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_CR2_v1_ttHbb_9J.h5",
                    basePath+"/files_Run2Legacy_v3/2018/preprocData_Run2Legacy_2018_VR_v1_ttHbb_9J.h5"],
        "output" : "~/Documents/PhD/LegacyRun2/LegacyRun2_AH_v3/TF4ttHFH/LegacyRun2_v3/2018/ttHbb_regionCompare_VR/9J/regionComp_9J_signal_MWSidebands",
        "plotType" : "plotDist",
        "normalized" : True,
        "Legend" : ["ttH(bb) ValTR", "ttH(bb) ValCR", "ttH(bb) VR"],
        "excludeVars" : ["*weight*", "*Weight*", "njets", "nPVs", "ttCls", "Wmass*", "nBDeepFlav*"],
        "lumi" : 59.7,
    },
}

if __name__ == "__main__":
    initLogging(30)
    for year in ["CompYears"]:#"2016","2017","2018","FullRun2"]:
        logging.warning("Processing year %s", year)
        for plot in plots:
            if year not in plot:
                continue
            logging.warning("Plotting %s", plot)
            plotSettings = plots[plot]


            styleConfig = StyleConfig(plotSettings["style"])

            inputDFs = checkInputData.getDataframes([filename for filename in plotSettings["inputs"]])

            vars2Process = checkInputData.generateVariableList(inputDFs[0], ["All"], plotSettings["excludeVars"])

            checkNcreateFolder(os.path.expanduser(plotSettings["output"]))

            if plotSettings["plotType"] == "plotDist":
                checkInputData.getDistributions(
                    styleConfig,
                    inputDFs,
                    os.path.expanduser(plotSettings["output"]),
                    vars2Process,
                    plotSettings["Legend"],
                    plotSettings["normalized"],
                    False,
                    plotSettings["lumi"],
                ) 
            else:
                raise NotImplementedError





    
